spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace